name       : lxcfs
version    : 5.0.2
release    : 5
source     :
    - https://linuxcontainers.org/downloads/lxcfs/lxcfs-5.0.2.tar.gz : c3df03629ee8955de60a28da7490350ad1eb7aa3134b6917d40ec68ef092d039
license    : LGPL-2.1-or-later
homepage   : https://linuxcontainers.org/lxcfs/
component  : virt
summary    : FUSE filesystem for LXC
description: |
    LXCFS is a small FUSE filesystem written with the intention of making Linux containers feel more like a virtual machine
builddeps  :
    - pkgconfig(fuse3)
    - help2man
    - lxc
    - python-jinja
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/lxcfs.tmpfiles $installdir/%libdir%/tmpfiles.d/lxcfs.conf
    install -Dm00644 $pkgfiles/lxcfs.service $installdir/%libdir%/systemd/system/lxcfs.service

    # Delete extra service file that luckily the install tries to stick under /lib/
    rm -rf $installdir/lib
    rm -rf $installdir/usr/lib
