name       : lxcfs
version    : 4.0.12
release    : 4
source     :
    - https://linuxcontainers.org/downloads/lxcfs/lxcfs-4.0.12.tar.gz : f502b7c99b5013e58f7d5c4117778c0bffe98532a42e023308eb72a287f0c969
license    : LGPL-2.1-or-later
homepage   : https://linuxcontainers.org/lxcfs/
component  : virt
summary    : FUSE filesystem for LXC
description: |
    LXCFS is a small FUSE filesystem written with the intention of making Linux containers feel more like a virtual machine
builddeps  :
    - pkgconfig(fuse3)
    - lxc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/lxcfs.tmpfiles $installdir/%libdir%/tmpfiles.d/lxcfs.conf
    install -Dm00644 $pkgfiles/lxcfs.service $installdir/%libdir%/systemd/system/lxcfs.service
